### PR TITLE
Github greeting actions added

### LINKED ISSUE #21: [Feature]: Add the github action workflow for greeting contributors
### Describe your improvement idea or feature request

The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

### How would you like to see it implemented?

Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

### How can we contact you (optional)

_No response_

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

### PR DESCRIPTION
**Pull request by praptisharma28**
closes #21

### CODE REVIEW

**Comment by praptisharma28** [comment]
@Pavel401 check it

**Comment by praptisharma28** [comment]
> @Pavel401 check it

@Pavel401 review it

**Comment by MabudAlam** [comment]
Comment out the .env file and make sure there are no errors in CI/CD
Screenshot 2024-01-26 at 12 38 49 AM

**Comment by praptisharma28** [comment]
ok @Pavel401

**Pull request merged**
