### PR TITLE
Refactor Services for Improved Performance and Maintainability

### LINKED ISSUE #4: Refactor Services for Improved Performance and Maintainability
# Description
## Problem
The current implementation of services in the JobHunt Mobile app may have areas for improvement in terms of performance, code readability, and maintainability. Identifying and addressing these issues will contribute to a more efficient and robust application.

## Solution
Refactor the services within the app to enhance performance, readability, and maintainability. Consider the following aspects during the refactoring process:

### Areas for Improvement
1. **Code Structure:** Review the current code structure and identify opportunities for modularization and organization.
2. **Performance Optimization:** Analyze the performance of existing services and implement optimizations where necessary to improve overall app responsiveness.
3. **Error Handling:** Enhance error handling mechanisms to provide informative and user-friendly error messages when issues arise.

### PR DESCRIPTION
**Pull request by praptisharma28**
closes #4

### CODE REVIEW

**Comment by praptisharma28** [comment]
@Pavel401 have a look.

**Comment by MabudAlam** [comment]
Screenshot 2024-01-30 at 12 23 49 AM
Jobs are not loading

**Comment by praptisharma28** [comment]
Though I didnt make any changes in the files but I will look again @Pavel401

**Comment by praptisharma28** [comment]
Done @Pavel401 , it was a minor error in env, dont know how I left it.

**Pull request merged**
